/**
 * Turns the old app's export (tables/*.json + files/) into load.sql: the raw
 * rows in legacy.src and the logo files in legacy.blobs, ready for import.sql.
 *
 *   node tools/legacy-import/build-load.mjs <exportDir> <out.sql>
 *
 * Nothing here maps or cleans anything: the raw rows go in as they were, and
 * every decision lives in import.sql where it can be read and re-run.
 */
import { readFileSync, readdirSync, writeFileSync, existsSync, statSync } from 'node:fs'
import { join, extname } from 'node:path'

const [exportDir, outFile] = process.argv.slice(2)
if (!exportDir || !outFile) {
  console.error('usage: node build-load.mjs <exportDir> <out.sql>')
  process.exit(1)
}

// Logs, analytics, one-time tokens and the old app's own SaaS billing: none of
// it means anything in the new app, so it is not loaded at all.
const SKIP = new Set([
  'access_audit_logs', 'app_activity_events', 'app_sessions', 'billing_events',
  'coupons', 'crm_webhook_events', 'fb_connections', 'fb_leads', 'fb_pages',
  'notification_deliveries', 'notifications', 'payment_orders', 'payment_receipt_tokens',
  'payment_transactions', 'plans', 'project_terms_email_logs', 'razorpay_webhook_events',
  'state_master', 'team_work_delivery_tokens', 'user_invitations',
])

const TAG = '$LGCY$'
const out = []
out.push('-- Generated by tools/legacy-import/build-load.mjs. Holds every studio\'s data: keep it private.')
out.push('create schema if not exists legacy;')
out.push('drop table if exists legacy.src;')
out.push('create table legacy.src (tbl text not null, r jsonb not null);')
out.push('drop table if exists legacy.blobs;')
out.push('create table legacy.blobs (bucket text not null, path text not null, mime text not null, b64 text not null, primary key (bucket, path));')

let rows = 0
const tablesDir = join(exportDir, 'tables')
for (const f of readdirSync(tablesDir).sort()) {
  const tbl = f.replace(/\.json$/, '')
  if (SKIP.has(tbl)) continue
  const data = JSON.parse(readFileSync(join(tablesDir, f), 'utf8'))
  for (let i = 0; i < data.length; i += 500) {
    const chunk = JSON.stringify(data.slice(i, i + 500))
    if (chunk.includes(TAG)) throw new Error(`${tbl} contains the quote tag ${TAG}`)
    out.push(`insert into legacy.src (tbl, r) select '${tbl}', value from jsonb_array_elements(${TAG}${chunk}${TAG}::jsonb);`)
  }
  rows += data.length
}
out.push('create index on legacy.src (tbl);')
out.push("create index on legacy.src ((r->>'company_id'));")

const MIME = { '.png': 'image/png', '.jpg': 'image/jpeg', '.jpeg': 'image/jpeg', '.webp': 'image/webp', '.svg': 'image/svg+xml', '.gif': 'image/gif', '.pdf': 'application/pdf' }
let blobs = 0
for (const bucket of ['company-branding', 'personal-expense-attachments']) {
  const manifest = join(exportDir, 'files', `${bucket}.manifest.json`)
  if (!existsSync(manifest)) continue
  for (const o of JSON.parse(readFileSync(manifest, 'utf8'))) {
    const p = join(exportDir, 'files', bucket, ...o.path.split('/'))
    if (!existsSync(p) || !statSync(p).isFile()) continue
    const mime = o.mimetype || MIME[extname(p).toLowerCase()] || 'application/octet-stream'
    const b64 = readFileSync(p).toString('base64')
    out.push(`insert into legacy.blobs values ('${bucket}', ${TAG}${o.path}${TAG}, '${mime.replace(/'/g, '')}', '${b64}');`)
    blobs++
  }
}

writeFileSync(outFile, out.join('\n') + '\n')
console.log(`load.sql: ${rows} rows, ${blobs} files -> ${outFile}`)
