// Hindi captions for the tutorials: English caption -> Hindi. The app's own
// button names stay in English (that is what is on the screen), in quotes.
export const HI = {
  // team (one person)
  'Add one person to your team': 'टीम में एक व्यक्ति जोड़ें',
  'Name, phone, role and a login': 'नाम, फ़ोन, काम और लॉगिन',
  'Pick “One by one”': '“One by one” चुनें',
  'Type their name and mobile': 'उनका नाम और मोबाइल लिखें',
  'Tap the job they get booked for': 'जिस काम के लिए बुक होते हैं, उस पर टैप करें',
  'Give a login: any email works as a username': 'लॉगिन दें: कोई भी ईमेल यूज़रनेम बन सकता है',
  'Press “Add to team”': '“Add to team” दबाएँ',
  'Ravi is on your team and can sign in.': 'रवि अब आपकी टीम में है और साइन इन कर सकता है।',
  'One person, added in a minute': 'एक व्यक्ति, एक मिनट में जुड़ गया',
  // team (bulk)
  'Add your team': 'अपनी टीम जोड़ें',
  'Add your whole team at once': 'पूरी टीम एक साथ जोड़ें',
  'The people who shoot and edit with you': 'जो लोग आपके साथ शूट और एडिट करते हैं',
  'Tap “Add your team”': '“Add your team” पर टैप करें',
  'One row per person: name and mobile': 'हर व्यक्ति की एक लाइन: नाम और मोबाइल',
  'Give a login: any email works, it is just a username': 'लॉगिन दें: कोई भी ईमेल चलेगा, यह बस यूज़रनेम है',
  'Freelancer? Switch them to Per shoot': 'फ़्रीलांसर हैं? “Per shoot” चुनें',
  'Add them, and you are done': 'जोड़ दें, बस हो गया',
  'Your team is in. Next: your first client.': 'आपकी टीम जुड़ गई। अगला: आपका पहला क्लाइंट।',
  'Your team, ready in a minute': 'आपकी टीम, एक मिनट में तैयार',
  // client
  'Add your first client': 'अपना पहला क्लाइंट जोड़ें',
  'The couple or family you are shooting for': 'वह कपल या परिवार जिनके लिए आप शूट कर रहे हैं',
  'Open Clients and press New client': '“Clients” खोलें और “New client” दबाएँ',
  'Type the client’s name': 'क्लाइंट का नाम लिखें',
  'Add their mobile number': 'उनका मोबाइल नंबर डालें',
  'Press Save client': '“Save client” दबाएँ',
  'Saved. Priya is in your client list.': 'सेव हो गया। प्रिया आपकी क्लाइंट लिस्ट में है।',
  'Every client, saved once, used everywhere': 'हर क्लाइंट एक बार सेव, हर जगह काम आए',
  // project (whole)
  'Create your first project': 'अपना पहला प्रोजेक्ट बनाएँ',
  'Days, deliverables and price in one place': 'दिन, डिलिवरेबल्स और कीमत, सब एक जगह',
  'Name the project and pick the client': 'प्रोजेक्ट का नाम लिखें और क्लाइंट चुनें',
  'Tap Haldi, then its date, time and hours': '“Haldi” पर टैप करें, फिर तारीख, समय और घंटे',
  'Then the Wedding the same way': 'फिर “Wedding” भी इसी तरह',
  'Tap what the client gets': 'क्लाइंट को जो मिलेगा, उस पर टैप करें',
  'Enter the price and any advance paid': 'कीमत और मिला हुआ एडवांस डालें',
  'Check it all, then Create project': 'सब जाँच लें, फिर “Create project”',
  'Done: the quotation is ready to send': 'हो गया: कोटेशन भेजने के लिए तैयार है',
  'Book it once, everything follows': 'एक बार बुक करें, बाकी सब अपने आप',
  // project step 1
  'Project step 1: who it’s for': 'प्रोजेक्ट स्टेप 1: किसके लिए है',
  'Name the project': 'प्रोजेक्ट का नाम लिखें',
  'Pick the client, or add a new one': 'क्लाइंट चुनें, या नया जोड़ें',
  'Press Next: Event days': '“Next: Event days” दबाएँ',
  'Done. Now add the days you shoot.': 'हो गया। अब शूट के दिन जोड़ें।',
  'One client, one project, all in one place': 'एक क्लाइंट, एक प्रोजेक्ट, सब एक जगह',
  // project step 2
  'Project step 2: the event days': 'प्रोजेक्ट स्टेप 2: इवेंट के दिन',
  'Each function with its date, hours and team': 'हर फ़ंक्शन की तारीख, घंटे और टीम',
  'Tap a function to add its day: Haldi': 'फ़ंक्शन पर टैप करके दिन जोड़ें: Haldi',
  'Pick the date and the start time': 'तारीख और शुरू होने का समय चुनें',
  'Tap how many hours it runs': 'कितने घंटे चलेगा, उस पर टैप करें',
  'Add requirements: who this day needs': '“Add requirements”: इस दिन किसकी ज़रूरत है',
  'Add the Wedding the same way': '“Wedding” भी इसी तरह जोड़ें',
  'Both days are set. Next: Deliverables': 'दोनों दिन तैयार। अगला: Deliverables',
  'Delivery dates count from these days': 'डिलीवरी की तारीखें इन्हीं दिनों से गिनी जाती हैं',
  'Plan every day once, the team follows': 'हर दिन एक बार प्लान करें, टीम साथ चले',
  // project step 3
  'Project step 3: what they get': 'प्रोजेक्ट स्टेप 3: क्लाइंट को क्या मिलेगा',
  'Album, film, teaser: tick what is in the package': 'एल्बम, फ़िल्म, टीज़र: पैकेज में जो है, उस पर टिक करें',
  'Tap each thing in the package': 'पैकेज की हर चीज़ पर टैप करें',
  'Each gets a due date from the wedding day': 'हर एक की ड्यू डेट शादी के दिन से तय होती है',
  'Press Next: Price': '“Next: Price” दबाएँ',
  'Done. Next, the package price.': 'हो गया। अगला: पैकेज की कीमत।',
  'What they get, with every due date set': 'क्या मिलेगा, हर ड्यू डेट के साथ',
  // project step 4
  'Project step 4: the price': 'प्रोजेक्ट स्टेप 4: कीमत',
  'The package price and any advance paid': 'पैकेज की कीमत और मिला हुआ एडवांस',
  'Type the package price': 'पैकेज की कीमत लिखें',
  'Already paid? Add the advance (optional)': 'एडवांस मिल गया? उसे डालें (ज़रूरी नहीं)',
  'Then Next: Review': 'फिर “Next: Review”',
  'The balance to collect is worked out': 'बाकी कितना लेना है, अपने आप निकल आता है',
  'Press Create project': '“Create project” दबाएँ',
  'Done: the quotation opens, ready to send': 'हो गया: कोटेशन खुल गया, भेजने के लिए तैयार',
  'Price it once, the balance keeps itself': 'कीमत एक बार डालें, बाकी हिसाब अपने आप',
  // leads
  'Add a lead and book it': 'लीड जोड़ें और बुक करें',
  'From the first call to a booked project': 'पहली कॉल से बुक हुए प्रोजेक्ट तक',
  'Tap “Add lead”': '“Add lead” पर टैप करें',
  'A number and a name is enough to start': 'शुरू करने के लिए नंबर और नाम काफ़ी है',
  'Pick the event and its date': 'इवेंट और उसकी तारीख चुनें',
  'Ready to book? Press “Book it”': 'बुक करना है? “Book it” दबाएँ',
  'Name the project, set the price, book it': 'प्रोजेक्ट का नाम, कीमत डालें, बुक करें',
  'Booked. You land on the quotation, ready to send.': 'बुक हो गया। कोटेशन खुल गया, भेजने के लिए तैयार।',
  'Every enquiry, one tap from booked': 'हर इन्क्वायरी, बुकिंग से बस एक टैप दूर',
  // quotation
  'Send your quotation': 'अपना कोटेशन भेजें',
  'Check it as the client sees it, then send the link': 'क्लाइंट की नज़र से देखें, फिर लिंक भेजें',
  'Your quotation fills in from the project': 'कोटेशन प्रोजेक्ट से अपने आप भर जाता है',
  'Check it first: open “Send to client”': 'पहले जाँचें: “Send to client” खोलें',
  '“See it as the client” shows their exact copy': '“See it as the client” से क्लाइंट वाली कॉपी दिखती है',
  'Looks right? Go back to your view': 'सही है? अपने व्यू पर वापस जाएँ',
  'Send it: “Send to client”, then Copy link': 'भेजें: “Send to client”, फिर “Copy link”',
  'Copied. Paste it on WhatsApp; the client can open it now.': 'कॉपी हो गया। WhatsApp पर भेजें, क्लाइंट अभी खोल सकता है।',
  'A quotation your client can open in one tap': 'ऐसा कोटेशन जो क्लाइंट एक टैप में खोले',
  // assign
  'Book your team for a shoot': 'शूट के लिए टीम बुक करें',
  'Who is free, what they are paid, booked in one go': 'कौन फ़्री है, कितना पेमेंट, एक बार में बुक',
  'Each day lists who it needs. Tap “Assign team”': 'हर दिन पर लिखा है किसकी ज़रूरत है। “Assign team” दबाएँ',
  'Choose a person for each role': 'हर रोल के लिए एक व्यक्ति चुनें',
  'Their pay fills in from their wedding rate': 'पेमेंट उनके वेडिंग रेट से अपने आप भरता है',
  '“2 of 2 chosen”: press Book': '“2 of 2 chosen”: “Book” दबाएँ',
  'Booked. Press Done': 'बुक हो गया। “Done” दबाएँ',
  'The Wedding day is staffed, with each person’s pay': 'वेडिंग का दिन टीम से भर गया, सबके पेमेंट के साथ',
  'Your crew, booked without a phone call': 'आपकी टीम, बिना फ़ोन किए बुक',
  // give work
  'Give editing work': 'एडिटिंग का काम दें',
  'Hand a film to an editor in one step': 'एक स्टेप में फ़िल्म एडिटर को सौंपें',
  'Open the project’s Post-Production tab': 'प्रोजेक्ट का “Post-Production” टैब खोलें',
  'Nobody on the teaser yet? Tap Start editing': 'टीज़र पर अभी कोई नहीं? “Start editing” दबाएँ',
  'Editors are listed with how much they already have': 'एडिटर्स के साथ दिखता है उनके पास कितना काम है',
  'The due date is filled in. Add a line of brief': 'ड्यू डेट भरी हुई है। एक लाइन का ब्रीफ़ लिखें',
  'Tap “Start editing with Kavya”': '“Start editing with Kavya” दबाएँ',
  'Now in Editing, on Kavya’s own list under My work': 'अब “Editing” में, काव्या की “My work” लिस्ट पर',
  'Every edit has an owner and a date': 'हर एडिट का एक ज़िम्मेदार और एक तारीख',
  // board
  'Run the production board': 'प्रोडक्शन बोर्ड चलाएँ',
  'Every edit by stage, late work first': 'हर एडिट स्टेज के हिसाब से, लेट काम सबसे ऊपर',
  'Late, due today, no editor: counted for you': 'लेट, आज ड्यू, बिना एडिटर: सब गिना हुआ',
  'Reels edited? Drag the card to the next stage': 'रील्स एडिट हो गईं? कार्ड को अगले स्टेज पर खींचें',
  'Switch to List: late work is always on top': '“List” पर जाएँ: लेट काम हमेशा ऊपर',
  'Tick the work that has nobody on it': 'जिस काम पर कोई नहीं, उस पर टिक करें',
  '“2 selected”: Give to… Kavya, both at once': '“2 selected”: “Give to…” काव्या, दोनों एक साथ',
  'Both are Kavya’s now, ready for her to start': 'दोनों अब काव्या के पास, शुरू करने के लिए तैयार',
  'All your editing work, on one board': 'आपका सारा एडिटिंग काम, एक बोर्ड पर',
  // team day
  'Your team’s day': 'आपकी टीम का दिन',
  'What a team member sees when they sign in': 'टीम मेंबर साइन इन करने पर क्या देखता है',
  'Ravi signs in: his day, in time order': 'रवि साइन इन करता है: उसका दिन, समय के क्रम में',
  'At the Haldi venue, he taps “I’ve reached”': 'हल्दी वेन्यू पर पहुँचकर “I’ve reached” दबाता है',
  'Tonight’s Sangeet: Confirm, so the studio knows': 'आज रात का संगीत: “Confirm”, ताकि स्टूडियो को पता रहे',
  'Starting the teaser? Tap “I’ve started”': 'टीज़र शुरू किया? “I’ve started” दबाएँ',
  'My work: every edit, its stage and days left': '“My work”: हर एडिट, उसका स्टेज और बचे दिन',
  'Reached, confirmed, editing: Ravi’s day is on track': 'पहुँचा, कन्फ़र्म किया, एडिटिंग: रवि का दिन सही चल रहा है',
  'Your team’s day, on their own login': 'आपकी टीम का दिन, उनके अपने लॉगिन पर',
  // payments
  'Record a payment': 'पेमेंट दर्ज करें',
  'See what is due, and mark money in': 'क्या बाकी है देखें, और आया पैसा दर्ज करें',
  'Late, due soon, later and received, at a glance': 'लेट, जल्द ड्यू, बाद में और मिला हुआ, एक नज़र में',
  'Tap Overdue to see who owes you': '“Overdue” दबाएँ, देखें किसका बाकी है',
  'Priya’s advance is 5 days late': 'प्रिया का एडवांस 5 दिन लेट है',
  'Open the invoice': 'इनवॉइस खोलें',
  'Tap “Add payment from client”': '“Add payment from client” दबाएँ',
  'Record payment: the amount is in. Pick UPI, add the UTR': 'Record payment: रकम भरी है। UPI चुनें, UTR डालें',
  'Paid. Now back to Money → Payments': 'पेमेंट हो गया। अब Money → Payments पर वापस',
  'Counted in Received, and nothing is overdue': '“Received” में गिना गया, अब कुछ लेट नहीं',
  'Know who has paid, and who has not': 'जानें किसने पेमेंट किया, किसने नहीं',
  // payouts
  'Pay your crew': 'अपनी टीम को पेमेंट करें',
  'Who you owe for shoots done, paid in a tap': 'हो चुके शूट का बकाया, एक टैप में पेमेंट',
  'Team → Pay → Team payouts: who you owe now': 'Team → Pay → Team payouts: अभी किसका बकाया है',
  'Ravi shot the wedding on 20 Sept. Tap Pay': 'रवि ने 20 सितंबर को शादी शूट की। “Pay” दबाएँ',
  'His UPI is here, and the amount is filled in': 'उसका UPI यहाँ है, और रकम भरी हुई है',
  'Pick how you paid, and add the UTR': 'कैसे पेमेंट किया चुनें, और UTR डालें',
  'Save, and it is paid': 'सेव करें, पेमेंट हो गया',
  'Ravi is paid. Only Neha’s ₹9,000 is still owed': 'रवि को पेमेंट हो गया। बस नेहा के ₹9,000 बाकी हैं',
  'Under All, Ravi’s shoot now shows as paid': '“All” में रवि का शूट अब “Paid” दिखता है',
  'Your crew, paid on time, every time': 'आपकी टीम, हर बार समय पर पेमेंट',
  // invoices
  'Send an invoice': 'इनवॉइस भेजें',
  'Made from the project, shared as a link': 'प्रोजेक्ट से बना, लिंक से भेजा',
  'On the project’s Billing, tap “Create invoice”': 'प्रोजेक्ट के “Billing” में “Create invoice” दबाएँ',
  'Priya and her project are already filled in': 'प्रिया और उसका प्रोजेक्ट पहले से भरे हैं',
  'Tap “Package”: the booked price fills in': '“Package” दबाएँ: बुक की हुई कीमत भर जाती है',
  '₹2,85,000, the price Priya booked at': '₹2,85,000, जिस कीमत पर प्रिया ने बुक किया',
  'Press “Save and send”': '“Save and send” दबाएँ',
  'Saved as INV-0001': 'INV-0001 के नाम से सेव हुआ',
  'Open it to share it': 'भेजने के लिए इसे खोलें',
  '“Client link” copies a link she can open': '“Client link” से क्लाइंट के लिए लिंक कॉपी होता है',
  'An invoice on Priya’s phone in a minute': 'एक मिनट में इनवॉइस प्रिया के फ़ोन पर',
  // expenses
  'Add an expense': 'खर्च जोड़ें',
  'Every cost on the right project, and who paid it': 'हर खर्च सही प्रोजेक्ट पर, और किसने दिया',
  'Tap “Add expense”': '“Add expense” दबाएँ',
  'Type the amount': 'रकम लिखें',
  'Pick a category from the list': 'लिस्ट से कैटेगरी चुनें',
  'Who paid? Ravi paid from his own pocket': 'किसने दिया? रवि ने अपनी जेब से दिया',
  'Put it on the project it belongs to': 'जिस प्रोजेक्ट का है, उस पर डालें',
  'Press “Add expense” to save it': 'सेव करने के लिए “Add expense” दबाएँ',
  'Counted: this month is now ₹29,000': 'गिना गया: इस महीने का खर्च अब ₹29,000',
  'And ₹8,500 is owed back to Ravi': 'और रवि को ₹8,500 वापस देने हैं',
  'The row says the project and who to pay back': 'लाइन में प्रोजेक्ट और किसे लौटाना है, दोनों लिखा है',
  'Every rupee spent, on the right project': 'हर खर्च किया रुपया, सही प्रोजेक्ट पर',
  // attendance
  'Turn on attendance': 'अटेंडेंस चालू करें',
  'Where your studio is, and when the day starts': 'स्टूडियो कहाँ है, और दिन कब शुरू होता है',
  'Settings → Attendance. It is off until you turn it on': 'Settings → Attendance. आप चालू करें तभी चलेगा',
  'Paste your studio’s Google Maps link': 'स्टूडियो का Google Maps लिंक पेस्ट करें',
  'How close counts as in? Pick a radius, then save': 'कितनी दूरी तक हाज़िर माना जाए? दायरा चुनें, सेव करें',
  'Set when the day starts and ends': 'दिन कब शुरू और कब खत्म होता है, सेट करें',
  'Tuesday off. Save working hours': 'मंगलवार छुट्टी। “Save working hours” दबाएँ',
  'On: your team checks in at the studio from today': 'चालू: आज से टीम स्टूडियो पर चेक इन करेगी',
  'Attendance that marks itself': 'अटेंडेंस जो अपने आप लगती है',
  // leave
  'Approve leave': 'छुट्टी मंज़ूर करें',
  'See what is left, then say yes in one tap': 'कितनी बची है देखें, फिर एक टैप में हाँ',
  'Open Team → Attendance & leave': 'Team → Attendance & leave खोलें',
  'Then “Leave & holidays”': 'फिर “Leave & holidays”',
  'Ravi asked for 15–16 Oct, and says why': 'रवि ने 15–16 अक्टूबर की छुट्टी माँगी है, वजह के साथ',
  'It checks his balance: 9 days left, this is 2': 'बैलेंस जाँचता है: 9 दिन बचे, यह 2 दिन की है',
  'Tap Approve. Ravi is told straight away': '“Approve” दबाएँ। रवि को तुरंत पता चल जाता है',
  'Balances now shows what he has left': '“Balances” में दिखता है कितनी बची है',
  'Leave decided in one tap': 'छुट्टी का फ़ैसला, एक टैप में',
  // asides
  "Each name says if they are free that day": "हर नाम के साथ लिखा है, उस दिन फ़्री है या नहीं",
  "Paste the reels’ link, then move it": "रील्स का लिंक पेस्ट करें, फिर आगे बढ़ाएँ",
  "Now waiting for your review": "अब आपके रिव्यू का इंतज़ार है",
  "The late teaser leads the list": "लेट टीज़र लिस्ट में सबसे ऊपर है",
  "So it shows under “To reimburse” until he is paid back": "जब तक पैसा लौटाया न जाए, यह “To reimburse” में दिखेगा",
  "It is listed on the project, marked Sent": "यह प्रोजेक्ट पर दिखता है, “Sent” के साथ",
  "This is the invoice Priya gets": "प्रिया को यही इनवॉइस मिलता है",
  "Copied. Paste it on WhatsApp; no login needed": "कॉपी हो गया। WhatsApp पर भेजें, लॉगिन की ज़रूरत नहीं",
  "“To approve” counts who is waiting": "“To approve” में दिखता है कौन इंतज़ार में है",
  "Approved, and Ravi gets a note": "मंज़ूर, और रवि को मैसेज चला जाता है",
  "Ravi: 7 of 12 casual days left this year": "रवि: इस साल 12 में से 7 कैज़ुअल छुट्टियाँ बचीं",
  "Opening it here is never counted as their view": "यहाँ खोलना क्लाइंट का देखना नहीं गिना जाता",
  "A shoot day: his attendance is the venue": "शूट का दिन: उसकी अटेंडेंस वेन्यू पर लगती है",
  "Reached, on time: that is today’s attendance": "समय पर पहुँचा: यही आज की अटेंडेंस है",
  "The teaser is in Editing, 6 days left": "टीज़र “Editing” में है, 6 दिन बचे",
  'The booked package is already on the first line': 'बुक किया पैकेज पहली लाइन में पहले से है',
}
