import { Tutorial, studio, sleep } from './lib.mjs'
const t = new Tutorial('client', { title: 'Add your first client', subtitle: 'The couple or family you are shooting for', steps: 4 })
const s = await studio({ name: 'Mehta Studios', owner: 'Asha Mehta', skipSetup: true })
const p = await t.open(s)
await t.goto('/clients')
const add = p.getByRole('button', { name: 'New client' }).first()
await add.waitFor({ timeout: 10000 })
await t.start()
await t.titleCard(2400)
await t.step('Open Clients and press New client', add, { hold: 1100 })
await t.click(add, { after: 900 })
const d = p.getByRole('dialog')
const name = d.getByPlaceholder('e.g. Priya Sharma')
await t.step('Type the client’s name', name, { hold: 900 })
await t.type(name, 'Priya Sharma')
const ph = d.getByPlaceholder('98765 43210')
await t.step('Add their mobile number', ph, { hold: 900 })
await t.type(ph, '9876501234')
await sleep(300)
const save = d.getByRole('button', { name: 'Save client' })
await t.step('Press Save client', save, { hold: 1000 })
await t.point(save); await t.layer('ripple'); await sleep(200)
await t.layer('spot', null)
await save.click()
await d.waitFor({ state: 'hidden', timeout: 8000 }).catch(() => {})
const toast = p.locator('[data-sonner-toast]').first()
await toast.waitFor({ timeout: 5000 }).catch(() => console.log('no toast'))
console.log('toast:', await toast.innerText().catch(() => ''))
await sleep(600)
await t.layer('hidePointer')
const row = p.locator('main').getByRole('row').filter({ hasText: 'Priya Sharma' }).first()
await t.say('Saved. Priya is in your client list.', row, { hold: 3000 })
await t.endCard('Every client, saved once, used everywhere', 3000)
await t.stop()
t.build()
