import { Tutorial, studio, sleep } from './lib.mjs'
import { withSpot, padEnd, frozen, sayHere } from './helpers.mjs'
import { seedLeave } from './x3/seed-leave.mjs'
// Run with TZ=Asia/Kolkata.
const t = new Tutorial('leave', { title: 'Approve leave', subtitle: 'See what is left, then say yes in one tap', steps: 6 })
const s = await studio({ name: 'Kapoor Films Leave', owner: 'Asha Mehta', skipSetup: true })
await seedLeave(s)
const p = await t.open(s)
const h = withSpot(t)
await t.goto('/dashboard')
await t.start()
await t.titleCard()
const team = p.getByRole('button', { name: 'Team', exact: true }).or(p.getByRole('link', { name: 'Team', exact: true })).first()
await t.step('Open Team → Attendance & leave', team, { hold: 1200 })
await h.click(team, { after: 500 })
const att = p.getByRole('link', { name: 'Attendance & leave' }).first()
await h.click(att, { after: 300 }); await h.unspot(); await sleep(1200)
const lh = p.getByRole('link', { name: 'Leave & holidays' }).or(p.getByRole('button', { name: 'Leave & holidays' })).first()
await t.step('Then “Leave & holidays”', lh, { hold: 1100 })
const toApprove = p.getByRole('button', { name: /To approve/ }).first()
await h.click(lh, { after: 100 }); await toApprove.waitFor(); await sleep(450)
await sayHere(t, '“To approve” counts who is waiting', toApprove, 1300)
await h.click(toApprove, { after: 300 }); await h.unspot(); await sleep(900)
await t.step('Ravi asked for 15–16 Oct, and says why', p.locator('main').getByText('Ravi Kumar').first().locator('xpath=ancestor::div[1]'), { hold: 2400 })
await t.step('It checks his balance: 9 days left, this is 2', p.getByText(/Has 9 days casual left/), { hold: 2600 })
const approve = p.getByRole('button', { name: 'Approve', exact: true })
await t.step('Tap Approve. Ravi is told straight away', approve, { hold: 1300 })
await h.click(approve, { after: 200 }); await h.unspot(); await t.layer('caption', null); await sleep(900)
await sayHere(t, 'Approved, and Ravi gets a note', p.locator('[data-sonner-toast]').first(), 2000)
const bal = p.getByRole('button', { name: 'Balances', exact: true })
await t.step('Balances now shows what he has left', bal, { hold: 1100 })
await h.click(bal, { after: 300 }); await h.unspot(); await sleep(1100)
await t.layer('hidePointer')
await sayHere(t, 'Ravi: 7 of 12 casual days left this year', p.locator('main li').filter({ hasText: 'Ravi Kumar' }).first(), 2800)
await t.endCard('Leave decided in one tap')
await t.stop()
padEnd(t); frozen(t); t.build()
