import { Tutorial, studio, sleep, api, phone } from './lib.mjs'
import { withSpot, padEnd, frozen } from './helpers.mjs'
const t = new Tutorial('leads', { title: 'Add a lead and book it', subtitle: 'From the first call to a booked project', steps: 5 })
const s = await studio({ name: 'Mehta Studios', owner: 'Asha Mehta', skipSetup: true })
for (const [name, ev, d, v] of [['Ravi Kumar', 'Wedding', '2026-12-05', 250000], ['Neha Singh', 'Engagement', '2026-11-20', 80000]]) {
  await api('/crm/leads', { token: s.token, method: 'POST', body: { name, phone: phone(), event_type: ev, event_date: d, deal_value: v } })
}
const p = await t.open(s)
const h = withSpot(t)
await t.goto('/follow-ups')
await t.start()
await t.titleCard()
const add = p.getByRole('button', { name: 'Add lead' }).first()
await t.step('Tap “Add lead”', add, { hold: 1200 })
await h.click(add, { after: 300 }); await h.unspot(); await sleep(900)
const dlg = p.getByRole('dialog', { name: 'Add a lead' })
await t.step('A number and a name is enough to start', dlg.getByPlaceholder('9876543210'), { hold: 1100 })
await h.type(dlg.getByPlaceholder('9876543210'), '9876501234')
await h.type(dlg.getByPlaceholder('Aanya Sharma'), 'Priya Sharma')
await t.step('Pick the event and its date', dlg.getByText("What's the event?"), { hold: 1100 })
await h.click(dlg.getByText("What's the event?"), { after: 700 })
await h.click(p.getByRole('option', { name: 'Wedding' }).first(), { after: 200 }); await h.unspot(); await sleep(500)
await h.click(dlg.locator('button[aria-label^="Date of"]'), { after: 700 })
const pop = p.locator('[data-radix-popper-content-wrapper]').last()
await h.click(pop.locator('button[aria-label*="Next Month"]'), { after: 350 })
await h.click(pop.locator('button[aria-label*="Next Month"]'), { after: 350 })
await h.click(pop.locator('button[aria-label*="December 12th"]'), { after: 200 }); await h.unspot(); await sleep(700)
const save = dlg.getByRole('button', { name: 'Add lead' })
await h.click(save, { after: 300 }); await h.unspot(); await sleep(1900)
const book = p.getByRole('button', { name: 'Book it' }).first()
await t.step('Ready to book? Press “Book it”', book, { hold: 1400 })
await h.click(book, { after: 300 }); await h.unspot(); await sleep(1000)
const bd = p.getByRole('dialog', { name: /Book Priya/ })
const pkg = bd.getByLabel(/Package/)
await t.step('Name the project, set the price, book it', pkg, { hold: 1200 })
const pn = bd.getByLabel('Project name')
await h.retype(pn, 'Priya & Rahul Wedding', 45); await sleep(300)
await h.retype(pkg, '250000', 80); await sleep(500)
await h.spot(bd.getByRole('button', { name: 'Book it' }))
await h.click(bd.getByRole('button', { name: 'Book it' }), { after: 300 }); await h.unspot(); await sleep(2900)
await t.say('Booked. You land on the quotation, ready to send.', p.locator('main div').filter({ hasText: 'Happy with the quotation' }).filter({ has: p.getByRole('button', { name: 'Create the invoice' }) }).last(), { hold: 2600 })
await t.endCard('Every enquiry, one tap from booked')
await t.stop()
padEnd(t); frozen(t); t.build()
