import { Tutorial, studio, sleep } from './lib.mjs'
import { seedPayouts } from './seeds.mjs'
const t = new Tutorial('payouts', { title: 'Pay your crew', subtitle: 'Who you owe for shoots done, paid in a tap', steps: 5 })
const s = await studio({ name: 'Mehta Studios', owner: 'Asha Mehta', skipSetup: true })
await seedPayouts(s)
const p = await t.open(s)
await t.goto('/team-payouts')
await t.start()
await t.titleCard()
const owedCard = p.locator('div').filter({ has: p.getByText('Owed now', { exact: true }) }).filter({ hasText: 'Shoots already done' }).last()
await t.step('Team → Pay → Team payouts: who you owe now', owedCard, { hold: 2200 })
const pay = p.locator('button:text-is("Pay")').nth(1)
await t.step('Ravi shot the wedding on 20 Sept. Tap Pay', pay, { hold: 1300 })
await t.click(pay, { after: 100 }); await t.layer('spot', null); await sleep(1200)
const dlg = p.getByRole('dialog')
await t.step('His UPI is here, and the amount is filled in', dlg.getByText('Pay to', { exact: false }).first().locator('xpath=ancestor::div[2]'), { hold: 2200, pad: 6 })
const mode = dlg.getByRole('combobox').first()
await t.step('Pick how you paid, and add the UTR', mode, { hold: 1000 })
await t.click(mode, { after: 700 })
await t.click(p.getByRole('option', { name: 'UPI', exact: true }), { after: 600 })
await t.type(dlg.getByPlaceholder('UTR / cheque no.'), '612093847215', { delay: 55 })
await sleep(300)
const save = dlg.getByRole('button', { name: 'Save', exact: true })
await t.step('Save, and it is paid', save, { hold: 1000 })
await t.click(save, { after: 100 }); await t.layer('spot', null); await t.layer('caption', null)
await sleep(1800)
await t.layer('hidePointer')
const cards = p.locator('div').filter({ has: owedCard }).filter({ hasText: 'Upcoming' }).last()
await t.say('Ravi is paid. Only Neha’s ₹9,000 is still owed', cards, { hold: 2800 })
const all = p.getByRole('button', { name: 'All', exact: true }).or(p.getByRole('tab', { name: 'All', exact: true })).first()
await t.click(all, { after: 1200 })
await t.layer('hidePointer')
await t.say('Under All, Ravi’s shoot now shows as paid', p.locator('div').filter({ hasText: '20 Sept 2026 · Candid Photographer' }).filter({ hasText: 'Paid' }).last(), { hold: 2800, pad: 6 })
await t.endCard('Your crew, paid on time, every time')
await t.stop()
t.build()
