import { Tutorial, sleep } from './lib.mjs'
import { setup, kit } from './wiz.mjs'
const t = new Tutorial('project', { title: 'Create your first project', subtitle: 'Days, deliverables and price in one place', steps: 6 })
const { p } = await setup(t)
const k = kit(t, p)
const { main } = k
const nameIn = p.getByPlaceholder('e.g. Aanya & Rahul Wedding')

await t.start()
await t.titleCard(2000)
await t.step('Name the project and pick the client', nameIn, { hold: 400 })
await k.key(nameIn, 'Priya & Arjun Wedding', 28)
const client = main.getByText('Priya Sharma').first()
await k.spot(client)
await k.tap(client, { after: 600 })
await k.goNext()

await t.step('Tap Haldi, then its date, time and hours', main.getByTitle('Add Haldi'), { hold: 400 })
await k.tap(main.getByTitle('Add Haldi'), { after: 700 })
await k.spotUnion(k.card(), k.durRow())
await k.date('20/11/2026')
await k.time('10:00 AM')
await k.hours('4', 500)

await t.step('Then the Wedding the same way', main.getByTitle('Add Wedding Day'), { hold: 400 })
await k.tap(main.getByTitle('Add Wedding Day'), { after: 700 })
await k.spotUnion(k.card(), k.durRow())
await k.date('21/11/2026')
await k.time('6:00 PM')
await k.hours('6', 500)
await k.goNext()

const teaser = main.getByRole('button', { name: 'Wedding Teaser', exact: true })
await t.step('Tap what the client gets', teaser, { hold: 400 })
await k.tap(teaser, { after: 400 })
await k.tap(main.getByRole('button', { name: 'Photo Album', exact: true }), { after: 500 })
await sleep(500)
await k.goNext()

const price = p.getByPlaceholder('150000', { exact: true })
await t.step('Enter the price and any advance paid', price, { hold: 400 })
await k.key(price, '250000', 55)
const adv = p.getByPlaceholder('50000', { exact: true })
await k.spot(adv)
await k.key(adv, '50000', 55)
await sleep(300)
await k.goNext()

const create = p.getByRole('button', { name: 'Create project' })
await t.step('Check it all, then Create project', null, { hold: 0 })
await k.spotUnion(main.getByText('Priya & Arjun Wedding').first(), main.getByText('Everything is ready').first(), 16)
await sleep(1000)
await k.spot(create)
await t.point(create); await t.layer('ripple'); await sleep(200)
await t.layer('spot', null)
await create.click()
await p.waitForURL(/quotation/, { timeout: 15000 })
await main.getByText('PROJECT QUOTATION').first().waitFor({ timeout: 10000 })
await sleep(900)
await t.layer('hidePointer')
await t.say('Done: the quotation is ready to send', null, { hold: 2000 })
await t.endCard('Book it once, everything follows')
await t.stop()
t.build()
