import { Tutorial, studio, sleep } from './lib.mjs'
const t = new Tutorial('team', { title: 'Add one person to your team', subtitle: 'Name, phone, role and a login', steps: 5 })
const s = await studio({ name: 'Mehta Studios', owner: 'Asha Mehta', skipSetup: true })
const p = await t.open(s)
await t.goto('/employees?add=choose')
await t.start()
await t.titleCard()
const one = p.getByRole('button', { name: /One by one/ })
await t.step('Pick “One by one”', one, { hold: 1300 })
await t.layer('spot', null)
await t.click(one, { after: 1300 })
await t.step('Type their name and mobile', p.getByPlaceholder('Full name'), { hold: 900 })
await t.type(p.getByPlaceholder('Full name'), 'Ravi Kumar')
await t.type(p.getByPlaceholder('9876543210'), '9876543210')
await sleep(400)
const role = p.getByRole('button', { name: 'Candid Photographer', exact: true })
await t.step('Tap the job they get booked for', role, { hold: 1200 })
await t.click(role, { after: 1200 })
const email = p.getByPlaceholder('name@example.com')
await t.step('Give a login: any email works as a username', email, { hold: 1000 })
await t.type(email, `ravi${Math.floor(Math.random()*9000+1000)}@mehta.studio`)
await t.type(p.getByPlaceholder('At least 6 characters'), 'ravi2026')
await sleep(500)
const add = p.getByRole('button', { name: 'Add to team' })
await t.step('Press “Add to team”', add, { hold: 1200 })
await t.click(add, { after: 300 })
await t.layer('spot', null)
await sleep(1800)
await t.say('Ravi is on your team and can sign in.', p.getByRole('dialog').last(), { hold: 2400 })
await t.endCard('One person, added in a minute')
await t.stop()
t.build()
